name: Build and tests
on:
  pull_request:
    branches:
      - vechain

jobs:
  run-tests-and-build-report:
    name: Test Smart Contracts with Hardhat
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Use Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@vechain'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

      - name: Install dependencies
        run: yarn install
    
      - name: Smart contract tests
        run: yarn test:ci


